In [2]:
try:
    file = open('Arquivo', 'r')
    file.write('Teste')
except IOError:
    print('Houve erro')
else:
    print('Não houve erro')

Houve erro

##### Tratar erros

In [15]:
import pandas as pd

try: 
    file = pd.read_csv('dados/aluguel.csv', sep = ';')
    print(file)
except IOError:
    print('Deu ruim')
else:
    print('Abriu')

                          Tipo                    Bairro  Quartos  Vagas  \
0                    Quitinete                Copacabana        1      0
1                         Casa           Jardim Botânico        2      0
2      Conjunto Comercial/Sala           Barra da Tijuca        0      4
3                  Apartamento                    Centro        1      0
4                  Apartamento              Higienópolis        1      0
5                  Apartamento              Vista Alegre        3      1
6                  Apartamento                  Cachambi        2      0
7           Casa de Condomínio           Barra da Tijuca        5      4
8           Casa de Condomínio                     Ramos        2      2
9      Conjunto Comercial/Sala                    Centro        0      3
10                 Apartamento                    Centro        1      0
11                 Apartamento                    Grajaú        2      1
12                 Apartamento       Lins de Vasconcelos        3      1
13                 Apartamento                Copacabana        1      0
14                   Quitinete                Copacabana        1      0
15                 Apartamento                Copacabana        4      3
16              Prédio Inteiro                  Botafogo        0      0
17                        Flat                  Botafogo        3      1
18          Casa de Condomínio                   Taquara        3      1
19                 Apartamento   Freguesia (Jacarepaguá)        3      0
20                 Apartamento           Barra da Tijuca        2      1
21                 Apartamento                    Tijuca        2      1
22          Casa de Condomínio           Barra da Tijuca        4      3
23                 Apartamento                    Olaria        3      1
24                 Apartamento                    Tijuca        2      1
25                        Flat                    Leblon        1      0
26     Conjunto Comercial/Sala             São Cristóvão        0      1
27                 Apartamento                   Ipanema        3      1
28                 Apartamento                    Tijuca        1      0
29                  Loja/Salão              Campo Grande        0      1
...                        ...                       ...      ...    ...
32930              Apartamento   Freguesia (Jacarepaguá)        2      1
32931                     Casa                    Centro        5      0
32932              Apartamento           Todos os Santos        3      0
32933              Apartamento  Recreio dos Bandeirantes        2      1
32934              Apartamento               Jacarepaguá        2      1
32935              Apartamento                    Leblon        1      1
32936              Apartamento                Copacabana        2      0
32937  Conjunto Comercial/Sala                    Centro        0      0
32938              Apartamento                Copacabana        1      0
32939  Conjunto Comercial/Sala           Barra da Tijuca        0      1
32940              Apartamento           Barra da Tijuca        2      1
32941              Apartamento           Barra da Tijuca        3      2
32942  Conjunto Comercial/Sala           Barra da Tijuca        0      1
32943              Apartamento           Barra da Tijuca        3      2
32944              Apartamento  Recreio dos Bandeirantes        3      2
32945                Quitinete                Copacabana        1      0
32946  Conjunto Comercial/Sala                    Centro        0      0
32947              Apartamento                    Leblon        3      0
32948  Conjunto Comercial/Sala                    Centro        0      0
32949              Apartamento                   Ipanema        3      1
32950              Apartamento                    Tijuca        1      0
32951              Apartamento            Vila Valqueire        2      0
32952       Casa de Condomínio           Barra da Tijuca        5      3
32953              Apartamento                     Méier        2      0
32954              Box/Garagem                    Centro        0      0
32955                Quitinete                    Centro        0      0
32956              Apartamento               Jacarepaguá        3      1
32957              Apartamento      São Francisco Xavier        2      1
32958              Apartamento                    Leblon        2      0
32959  Conjunto Comercial/Sala                    Centro        0      0

       Suites  Area    Valor  Condominio    IPTU
0           0    40   1700.0       500.0    60.0
1           1   100   7000.0         NaN     NaN
2           0   150   5200.0      4020.0  1111.0
3           0    15    800.0       390.0    20.0
4           0    48    800.0       230.0     NaN
5           0    70   1200.0         NaN     NaN
6           0    50   1300.0       301.0    17.0
7           5   750  22000.0         NaN     NaN
8           0    65   1000.0         NaN     NaN
9           0   695  35000.0     19193.0  3030.0
10          0    36   1200.0         NaN     NaN
11          0    70   1500.0       642.0    74.0
12          1    90   1500.0       455.0    14.0
13          1    40   2000.0       561.0    50.0
14          0    27   1800.0       501.0     NaN
15          1   243  13000.0      2000.0   803.0
16          0   536  28000.0         NaN  3563.0
17          1    80   3800.0      1040.0     NaN
18          1   115   2000.0         NaN     NaN
19          0    54    950.0       300.0    28.0
20          1    67   1700.0       589.0   147.0
21          0   110   1900.0       700.0   138.0
22          2   466   7500.0      2695.0     NaN
23          0    68   1000.0       670.0     NaN
24          0    78   2000.0       700.0     NaN
25          0    56   4500.0      1900.0  1500.0
26          0    25   1100.0       600.0     NaN
27          1   125   7000.0      2100.0   463.0
28          0    48    750.0       772.0    25.0
29          0    35   1300.0       950.0     NaN
...       ...   ...      ...         ...     ...
32930       0    60    500.0       900.0   148.0
32931       1   160   5000.0         NaN    80.0
32932       0    54   1500.0       289.0    35.0
32933       1   105   2100.0       648.0   156.0
32934       1    78   2200.0       790.0   180.0
32935       1    50   4300.0      1730.0   259.0
32936       1    70   4100.0       700.0    90.0
32937       0   150  10000.0      2680.0   800.0
32938       0    50   1950.0       450.0    70.0
32939       0    36   1100.0      1200.0   270.0
32940       1    85   2250.0      1561.0   197.0
32941       0    98   2300.0       887.0   177.0
32942       0    55   2000.0      1096.0     NaN
32943       2   140   5500.0      1900.0   700.0
32944       1    88   1550.0       790.0     NaN
32945       0    22   1500.0       286.0   200.0
32946       0   140   4000.0      1412.0   496.0
32947       1    80   3000.0      1010.0   249.0
32948       0    32    600.0      1035.0    83.0
32949       2   150  15000.0      1400.0   600.0
32950       0    28   1000.0       360.0    25.0
32951       0    52   1000.0       550.0     NaN
32952       4   450  15000.0      1711.0  2332.0
32953       0    70    900.0       490.0    48.0
32954       0   755  14000.0         NaN     NaN
32955       0    27    800.0       350.0    25.0
32956       2    78   1800.0       800.0    40.0
32957       0    48   1400.0       509.0    37.0
32958       0    70   3000.0       760.0     NaN
32959       0   250   6500.0      4206.0  1109.0

[32960 rows x 9 columns]
Abriu

In [ ]:
try:
    data =